version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5435:5432"  # Exposing PostgreSQL on port 5435
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: testing
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: